export type Language='pt'|'en';

const exact:Record<string,string>={
 'Biblioteca':'Library','Importar':'Import','Explorar':'Explore','Guia de digitação':'Fingering guide','Importar partitura':'Import score','Visão geral':'Overview','Modo de prática':'Practice mode','Transversal · 12 furos':'Transverse · 12 holes','Alto C · 12 furos':'Alto C · 12 holes','MusicXML, MXL ou MIDI':'MusicXML, MXL or MIDI','compassos':'measures','compassos com repetições':'measures with repeats','eventos':'events','parte(s)':'part(s)','voz(es)':'voice(s)','tempo':'beat','tempos':'beats','Compasso':'Measure','Nota':'Note','Voz':'Voice','pauta':'staff','sugerida':'suggested','de':'of','para':'to','tocar':'play','pausar':'pause','casa':'ending','ligadura':'tie','Progresso':'Status','Ordenar':'Sort',
 'Sua biblioteca.':'Your library.','Sua biblioteca':'Your library','Importar uma melodia.':'Import a melody.','Importar uma melodia':'Import a melody','Trocar arquivo':'Change file',
 'Todas as músicas':'All songs','Favoritas':'Favorites','Todos os estados':'All statuses','Buscar na biblioteca':'Search library','Recentes':'Recent','Título A–Z':'Title A–Z','Importadas recentemente':'Recently imported','Por compositor':'By composer','Por origem':'By source',
 'SUA PRIMEIRA MELODIA':'YOUR FIRST MELODY','CONTINUE DE ONDE PAROU':'CONTINUE WHERE YOU LEFT OFF','Praticar agora':'Practice now','Praticar':'Practice','Pronta para tocar':'Ready to play','Uma nova melodia':'A new melody','Importe uma partitura':'Import a score','para praticar.':'to practice.','Biblioteca salva neste dispositivo':'Library saved on this device','Exportar backup':'Export backup','Restaurar backup':'Restore backup',
 'Aprendendo':'Learning','Quase pronta':'Almost ready','Dominada':'Mastered','Progresso da música':'Song progress','Alterar':'Change',
 'IMPORTAÇÃO':'IMPORT','Lendo sua partitura…':'Reading your score…','Deixe sua partitura aqui':'Drop your score here','Arraste o arquivo ou escolha uma partitura no dispositivo.':'Drag the file here or choose a score from your device.','Processando…':'Processing…','Escolher arquivo':'Choose file','Experimentar a composição original':'Try the original composition',
 'MIDI também funciona: escolha a faixa da melodia antes de salvar. PDF e imagens ainda exigem conversão em um editor de partituras.':'MIDI also works: choose the melody track before saving. PDF and images still require conversion in a score editor.',
 'PARTITURA RECONHECIDA':'SCORE RECOGNIZED','Parte / instrumento':'Part / instrument','Voz e pauta':'Voice and staff','Como tratar acordes e sobreposições':'How to handle chords and overlaps','Manter a voz escolhida':'Keep selected voice','Manter a nota mais aguda':'Keep highest note','Manter a nota mais grave':'Keep lowest note','Todas as vozes desta parte':'All voices in this part',
 'Transposição por semitons':'Transpose by semitones','Descer um semitom':'Down one semitone','Subir um semitom':'Up one semitone','Adaptação para ocarina':'Ocarina adaptation','Original · apenas transposição manual':'Original · manual transposition only','Preservar tonalidade ao máximo':'Preserve key as much as possible','Recomendado · preservar tom quando natural':'Recommended · preserve key when natural','Flexível · priorizar a melodia tocável':'Flexible · prioritize a playable melody','Simplificar música':'Simplify music','Melhor encaixe:':'Best fit:',
 'O original permanece salvo. Escolha Original e desative a simplificação para restaurá-lo. As porcentagens são estimativas heurísticas.':'The original remains saved. Choose Original and turn off simplification to restore it. Percentages are heuristic estimates.','Notas dentro do alcance':'Notes within range','Confira os avisos da importação':'Review import warnings','Pausar prévia':'Pause preview','Ouvir prévia':'Listen to preview','Salvar e praticar':'Save and practice','PRÉVIA DA DIGITAÇÃO':'FINGERING PREVIEW','Sequência de digitações':'Fingering sequence',
 'Não foi possível concluir':'Could not complete','Fechar aviso':'Dismiss notice','Preparando seu espaço…':'Preparing your space…','Abrindo a biblioteca deste dispositivo.':'Opening this device’s library.','Importação concluída. Sua música já está salva neste dispositivo.':'Import complete. Your song is now saved on this device.','O cache offline não pôde ser ativado neste navegador.':'Offline cache could not be enabled in this browser.',
 'Ocarina em C':'Ocarina in C','Sua música, neste dispositivo':'Your music, on this device','Offline · biblioteca disponível':'Offline · library available','Instalar Sopro':'Install Sopro','Sopro, biblioteca':'Sopro, library','Ir ao conteúdo':'Skip to content',
 'Ajustar melodia':'Adjust melody','Melodia e adaptações aplicadas':'Melody and applied adaptations','Transpor':'Transpose','PREPARE O SOPRO':'GET READY','TOQUE AGORA':'PLAY NOW','ANTERIOR':'PREVIOUS','A SEGUIR':'NEXT','PRÓXIMAS':'UP NEXT','Sem notas':'No notes','Fechado':'Closed','Aberto':'Open','Muda a seguir':'Changes next',
 'Do seu jeito':'Your way','Velocidade':'Speed','Afinação preservada':'Pitch preserved','Metrônomo':'Metronome','Contagem de entrada':'Count-in','Mostrar pausas':'Show rests','Destacar troca de dedos':'Highlight fingering changes','Repetir trecho':'Repeat section','Do compasso':'From measure','Até o compasso':'To measure','Compasso inicial':'First measure','Compasso final':'Last measure','Use a posição na sequência, incluindo as repetições.':'Use the position in the sequence, including repeats.','Volume':'Volume','Atalhos de teclado':'Keyboard shortcuts',
 'Reiniciar':'Restart','Nota anterior':'Previous note','Próxima nota':'Next note','Reproduzir':'Play','Pausar':'Pause','Pronto para tocar':'Ready to play','espaço':'space','para tocar':'to play','para pausar':'to pause','Ligadura de prolongamento':'Tie','COMPASSO':'MEASURE',
 'CONHEÇA SEU INSTRUMENTO':'KNOW YOUR INSTRUMENT','Perfil transversal Alto C · alturas reais Lá4 a Fá6.':'Alto C transverse profile · actual pitches A4 to F6.','Leia como quem toca':'Read it as you play','Dez furos na parte superior: oito principais e dois subfuros menores. Os dois círculos separados representam os polegares, na parte inferior.':'Ten holes on top: eight main holes and two smaller subholes. The two separate circles represent the thumb holes underneath.','Preencha os furos escuros e deixe livres os claros. O contorno dourado mostra os dedos que mudam na próxima nota.':'Cover the dark holes and leave the light ones open. The gold outline shows which fingers change on the next note.','As tabelas de referência escrevem uma oitava abaixo do som real. O Sopro usa a altura real: Dó5 soa como Dó5. Ajuste a transposição quando necessário.':'Reference charts write one octave below the actual sound. Sopro uses concert pitch: C5 sounds as C5. Adjust transposition when needed.','Fontes e variações':'Sources and variations','Digitações conferidas nas tabelas da STL Ocarina e Imperial City Ocarina. Os diagramas do Sopro são próprios. Instrumentos de outros fabricantes podem exigir posições diferentes, especialmente nos acidentes.':'Fingerings checked against STL Ocarina and Imperial City Ocarina charts. Sopro uses its own diagrams. Instruments from other makers may require different fingerings, especially for accidentals.','STL · tabela de doze furos em C':'STL · twelve-hole C chart','Imperial City · tabela Alto C':'Imperial City · Alto C chart','Baixar composição original (CC0)':'Download original composition (CC0)',
 'NOVAS MELODIAS PARA O SEU REPERTÓRIO':'NEW MELODIES FOR YOUR REPERTOIRE','Deixe a música chegar.':'Let the music in.','Deixe a música chegar':'Let the music in','Dos seus jogos e animes favoritos para os dedos. Busque, importe e pratique aqui.':'From your favorite games and anime to your fingertips. Search, import, and practice here.','Fonte de partituras':'Score source','Ordenar catálogo':'Sort catalog','Somente importáveis':'Importable only','Relevância':'Relevance','Mais populares':'Most popular','Buscar no catálogo':'Search catalog','Buscando…':'Searching…','Buscar partituras':'Search scores','Arranjos de jogos e anime do Ichigo’s, para uso pessoal e não comercial.':'Game and anime arrangements from Ichigo’s, for personal and non-commercial use.','Busque pelo jogo, anime ou nome da música. “Somente importáveis” mostra transcrições com MIDI.':'Search by game, anime, or song name. “Importable only” shows transcriptions with MIDI.','MIDI público do Ice’s Zelda Central, importado e convertido dentro do Sopro.':'Public MIDI from Ice’s Zelda Central, imported and converted inside Sopro.','Amostra curada do PDMX em MXL, restrita a no_license_conflict.':'Curated PDMX sample in MXL, restricted to no_license_conflict.','Acervo PublicJukebox; popularidade usa acessos do Archive.':'PublicJukebox collection; popularity uses Archive views.','Edições CC0 do OpenScore Lieder.':'CC0 editions from OpenScore Lieder.',
 'Escolha uma fonte e busque por título ou autor. Deixe o campo vazio para navegar pelo acervo.':'Choose a source and search by title or author. Leave the field empty to browse the collection.','Créditos':'Credits','Formato sem importação':'Format cannot be imported','Anterior':'Previous','Próxima':'Next','Nenhuma partitura nesta busca':'No scores found','Um repertório para descobrir':'A repertoire to discover','Experimente outro título ou autor.':'Try another title or author.','Explore temas de jogos e anime, obras em domínio público, canções clássicas e partituras históricas nas fontes disponíveis do catálogo.':'Explore game and anime themes, public-domain works, classical songs, and historical scores from the available catalog sources.',
 'Créditos da partitura':'Score credits','Transcrição / edição:':'Transcription / edition:','Os créditos são preservados ao importar.':'Credits are preserved on import.','Voltar ao catálogo':'Back to catalog','Escolha a partitura':'Choose a score','Arquivo da partitura':'Score file','Transcrições automáticas podem conter erros. Você poderá escolher a melodia e ouvir uma prévia antes de salvar.':'Automatic transcriptions may contain errors. You can choose the melody and listen to a preview before saving.','Importar arquivo selecionado':'Import selected file','Páginas do catálogo':'Catalog pages',
 'Excluir esta música?':'Delete this song?','Cancelar':'Cancel','Excluir música':'Delete song','Editar informações':'Edit information','Personalize os dados exibidos na biblioteca.':'Customize the information shown in the library.','Título':'Title','Compositor':'Composer','Salvar informações':'Save information','Fechar':'Close','Sobre o Sopro':'About Sopro','Idealizado por Ítalo Araújo, com carinho para Manu Zancatt.':'Conceived by Ítalo Araújo, with love for Manu Zancatt.','Desenvolvido com apoio do ChatGPT, da OpenAI.':'Developed with support from ChatGPT by OpenAI.','Atalhos para praticar':'Practice shortcuts','Disponíveis quando o foco está fora dos controles.':'Available when focus is outside the controls.','Espaço':'Space','Reproduzir / pausar':'Play / pause','Nota anterior / próxima':'Previous / next note','Voltar ao início':'Return to start','Abrir esta ajuda':'Open this help',
 'Pausa':'Rest','Fora do alcance':'Out of range','Pausa: não sopre':'Rest: do not blow','Ocarina de doze furos':'Twelve-hole ocarina','Ocarina Alto C':'Alto C ocarina','POLEGARES':'THUMBS','Polegar esquerdo':'Left thumb','Polegar direito':'Right thumb','Vista de quem toca. Polegares destacados abaixo.':'Player’s view. Thumb holes highlighted below.','Créditos da capa':'Cover credits','Imagem da Wikipédia':'Wikipedia image',
 'Ichigo’s · jogos e anime':'Ichigo’s · games and anime','Temas geek em MIDI · uso não comercial':'Geek MIDI themes · non-commercial use','Zelda Central MIDI':'Zelda Central MIDI','PDMX · domínio público':'PDMX · public domain','Amostra curada em MXL · sem conflito de licença':'Curated MXL sample · no license conflict','Canções em MXL · edições CC0':'Songs in MXL · CC0 editions','Internet Archive · PublicJukebox':'Internet Archive · PublicJukebox','Partituras históricas · MusicXML e PDF':'Historical scores · MusicXML and PDF','VGLeadSheets · indisponível':'VGLeadSheets · unavailable','Índice geek · PDF não importável':'Geek index · PDF cannot be imported','VGMusic · indisponível':'VGMusic · unavailable','Ligação direta não permitida':'Direct linking not allowed','NinSheetMusic · indisponível':'NinSheetMusic · unavailable','Verificação antirobô':'Anti-bot verification',
};

const replacements:[RegExp,string][]=[
 [/Compositor não informado(?: pela fonte)?/gi,'Composer not provided'],[/Autoria não informada/gi,'Author not provided'],[/Transcritor não informado/gi,'Transcriber not provided'],[/composição original/gi,'original composition'],[/domínio público/gi,'public domain'],[/Uso pessoal e não comercial/gi,'Personal and non-commercial use'],
 [/(\d+) parte\(s\)/g,'$1 part(s)'],[/(\d+) voz\(es\)/g,'$1 voice(s)'],[/(\d+) compassos/g,'$1 measures'],[/(\d+) eventos/g,'$1 events'],[/Compasso ([\w.-]+)/g,'Measure $1'],[/compasso ([\w.-]+)/g,'measure $1'],[/Nota (\d+) de (\d+)/g,'Note $1 of $2'],[/Página (\d+) de (\d+)/g,'Page $1 of $2'],[/Praticada em /g,'Practiced on '],[/ notas fora do alcance/g,' notes out of range'],[/notas fora de Lá4–Fá6/g,'notes outside A4–F6'],[/O áudio mantém as alturas originais/g,'Audio keeps the original pitches'],
 [/voz original/g,'original voice'],[/\bVoz\b/g,'Voice'],[/\bvoz\b/g,'voice'],[/\bpauta\b/g,'staff'],[/sugerida/g,'suggested'],[/todas as vozes/g,'all voices'],[/nota mais aguda/g,'highest note'],[/nota mais grave/g,'lowest note'],[/transposição/g,'transposition'],[/versão simplificada/g,'simplified version'],[/notas mudaram de oitava/g,'notes changed octave'],[/notas removidas/g,'notes removed'],[/preservação estimada/g,'estimated preservation'],[/voice original/g,'original voice'],[/Lá4–Fá6/g,'A4–F6'],
 [/ itens na fonte/g,' items in source'],[/Resultados em cache/g,'Cached results'],[/Consultado em/g,'Retrieved on'],[/acessos no Archive/g,'Archive views'],[/Fonte:/g,'Source:'],[/Arquivo não encontrado na fonte\./g,'File not found at source.'],[/Fonte indisponível\./g,'Source unavailable.'],
 [/ contém mais de um arquivo compatível\. Escolha o arquivo que deseja praticar\./g,' contains more than one compatible file. Choose the file you want to practice.'],[/ será removida deste dispositivo\. Exporte um backup para guardar uma cópia\./g,' will be removed from this device. Export a backup to keep a copy.'],[/ música\(s\) restaurada\(s\)\./g,' song(s) restored.'],
 [/(\d+(?:,\d+)?) tempo\b/g,'$1 beat'],[/(\d+(?:,\d+)?) tempos\b/g,'$1 beats'],
 [/mínimo esquerdo/g,'left little finger'],[/anelar esquerdo/g,'left ring finger'],[/médio esquerdo/g,'left middle finger'],[/indicador esquerdo/g,'left index finger'],[/mínimo direito/g,'right little finger'],[/anelar direito/g,'right ring finger'],[/médio direito/g,'right middle finger'],[/indicador direito/g,'right index finger'],[/polegar esquerdo/g,'left thumb'],[/polegar direito/g,'right thumb'],[/fechado/g,'closed'],[/aberto/g,'open'],
 [/A fonte demorou para responder\. Tente novamente\./g,'The source took too long to respond. Try again.'],[/Sem conexão\. Sua biblioteca continua disponível\./g,'No connection. Your library remains available.'],[/Não foi possível consultar os arquivos\./g,'Could not retrieve the files.'],[/Não há arquivo compatível disponível neste item\. Escolha outra transcrição\./g,'No compatible file is available for this item. Choose another transcription.'],[/Escolha MusicXML, MXL ou MIDI \(\.mid\/\.midi\)\. PDF não é compatível\./g,'Choose MusicXML, MXL, or MIDI (.mid/.midi). PDF is not supported.'],[/Arquivo muito grande\. O limite é 8 MB\./g,'File too large. The limit is 8 MB.'],[/XML inválido\. Confira o arquivo e exporte novamente\./g,'Invalid XML. Check the file and export it again.'],[/MIDI inválido\. Exporte novamente como MIDI tipo 0 ou 1\./g,'Invalid MIDI. Export it again as MIDI type 0 or 1.'],
];

export function translateUi(value:string){
 const leading=value.match(/^\s*/)?.[0]||'',trailing=value.match(/\s*$/)?.[0]||'',body=value.trim();
 if(!body)return value;
 let translated=exact[body]||body;
 for(const [pattern,replacement] of replacements)translated=translated.replace(pattern,replacement);
 translated=translated.replace(/(\d),(\d)/g,'$1.$2');
 return `${leading}${translated}${trailing}`;
}
