import {test,expect} from '@playwright/test';
import {demoXML} from '../../core/music/demo';
const errors:string[]=[];
test('import → melody selection → diagrams → playback → speed → loop → save → reload → offline',async({page,context})=>{
 page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{name:'Sua biblioteca.'})).toBeVisible();
 await page.getByRole('button',{name:'Importar partitura',exact:true}).click();await expect(page.getByRole('heading',{name:'Importar uma melodia.'})).toBeVisible();
 await page.getByLabel('Arquivo MusicXML ou MIDI',{exact:true}).setInputFiles({name:'ensaio.musicxml',mimeType:'application/xml',buffer:Buffer.from(demoXML.replaceAll('Jardim ao anoitecer','Ensaio de integração'))});
 await expect(page.getByText('PARTITURA RECONHECIDA')).toBeVisible();await expect(page.getByLabel('Parte / instrumento')).toContainText('Ocarina');await expect(page.getByLabel('Voz e pauta')).toContainText('Voz 1');
 await page.getByRole('button',{name:'Ouvir prévia'}).click();await expect(page.getByRole('button',{name:'Pausar prévia'})).toBeVisible();await page.getByRole('button',{name:'Pausar prévia'}).click();
 await page.getByRole('button',{name:'Salvar e praticar'}).click();await expect(page.getByRole('heading',{name:'Ensaio de integração'})).toBeVisible();await expect(page.locator('.measure')).toHaveCount(12);await expect(page.locator('.note-card').first().locator('svg circle')).toHaveCount(12);
 await page.locator('.view-switch').getByRole('button',{name:'Praticar',exact:true}).click();await page.getByRole('switch',{name:'Contagem de entrada'}).click();
 await page.getByRole('button',{name:'Reproduzir',exact:true}).click();await expect(page.getByRole('button',{name:'Pausar',exact:true})).toBeVisible();await expect.poll(async()=>page.locator('.transport-info small').innerText()).not.toBe('Nota 1 de 49');
 const speed=page.getByRole('slider',{name:'Velocidade'});await speed.fill('75');await expect(page.getByRole('button',{name:'Pausar',exact:true})).toBeVisible();await expect(page.locator('.range-field').first()).toContainText('75%');
 await page.getByRole('button',{name:'Pausar',exact:true}).click();await page.getByRole('spinbutton',{name:'Compasso inicial',exact:true}).fill('2');await page.getByRole('spinbutton',{name:'Compasso final',exact:true}).fill('3');await page.getByRole('switch',{name:'Repetir trecho'}).click();await expect(page.getByRole('button',{name:'Repetir trecho',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'Reproduzir',exact:true}).click();await expect(page.getByRole('button',{name:'Pausar',exact:true})).toBeVisible();await page.getByRole('button',{name:'Pausar',exact:true}).click();
 await page.getByRole('button',{name:'Voltar à biblioteca'}).click();await page.reload();await expect(page.getByRole('button',{name:'Ensaio de integração',exact:true})).toBeVisible();await page.getByRole('button',{name:'Ensaio de integração',exact:true}).click();await page.locator('.view-switch').getByRole('button',{name:'Praticar',exact:true}).click();await expect(speed).toHaveValue('75');
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await expect.poll(async()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);
 await context.setOffline(true);await page.reload();await expect(page.getByRole('heading',{name:'Sua biblioteca.'})).toBeVisible();await expect(page.getByRole('button',{name:'Ensaio de integração',exact:true})).toBeVisible();await page.getByRole('button',{name:'Ensaio de integração',exact:true}).click();await page.getByRole('button',{name:'Reproduzir',exact:true}).click();await expect(page.getByRole('button',{name:'Pausar',exact:true})).toBeVisible();await page.getByRole('button',{name:'Pausar',exact:true}).click();expect(errors).toEqual([]);
});
test('mobile and desktop visual checks, import error and keyboard focus',async({page})=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:'Sua biblioteca.'})).toBeVisible();await page.screenshot({path:'../../work/qa-library-desktop.png',fullPage:true});await page.getByRole('button',{name:'Praticar agora'}).click();await expect(page.getByText('TOQUE AGORA',{exact:true})).toBeVisible();await page.screenshot({path:'../../work/qa-practice-desktop.png',fullPage:true});
 for(const width of [390,320,768]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.getByRole('button',{name:'Reproduzir',exact:true})).toBeInViewport();await page.screenshot({path:`../../work/qa-practice-${width}.png`,fullPage:true});}
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Voltar à biblioteca'}).click();await page.screenshot({path:'../../work/qa-library-mobile.png',fullPage:true});await page.getByRole('button',{name:'Importar partitura',exact:true}).click();await expect(page.getByRole('heading',{name:'Importar uma melodia.'})).toBeVisible();await page.getByLabel('Arquivo MusicXML ou MIDI',{exact:true}).setInputFiles({name:'invalid.xml',mimeType:'application/xml',buffer:Buffer.from('<bad>')});await expect(page.getByRole('alert')).toContainText('XML inválido');await page.getByRole('button',{name:'Fechar aviso'}).click();await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement?.tagName)).not.toBe('BODY');
});

test('live OpenScore search and import from the real CC0 source',async({page})=>{
 test.skip(!process.env.SOPRO_CATALOG_TEST,'Enable SOPRO_CATALOG_TEST=1 to query the real public source.');
 await page.goto('/');await page.getByRole('button',{name:'Explorar',exact:true}).click();await page.getByRole('combobox',{name:'Fonte de partituras'}).click();await page.getByRole('option',{name:'OpenScore Lieder',exact:true}).click();await page.getByRole('textbox',{name:'Buscar no catálogo'}).fill('Just for Today');await page.getByRole('button',{name:'Buscar partituras'}).click();await expect(page.locator('.catalog-result').first()).toContainText('Abbott');await page.locator('.catalog-result').first().getByRole('button',{name:'Importar',exact:true}).click();await expect(page.getByText('PARTITURA RECONHECIDA')).toBeVisible();await expect(page.getByLabel('Parte / instrumento')).toBeVisible();await expect(page.getByRole('button',{name:'Salvar e praticar'})).toBeEnabled();
});
