import {test,expect} from '@playwright/test';
import midiPackage from '@tonejs/midi';
const {Midi}=midiPackage;
const live=!!process.env.SOPRO_CATALOG_TEST;
async function source(page:any,name:string){await page.getByRole('combobox',{name:'Fonte de partituras'}).click();await page.getByRole('option',{name,exact:true}).click();}
test('MIDI file → track selection → practice → reload → offline with the MIDI module cached',async({page,context})=>{
 const midi=new Midi();midi.name='Melodia MIDI de teste';midi.addTrack().addNote({midi:72,ticks:0,durationTicks:480}).addNote({midi:74,ticks:480,durationTicks:960});
 await page.goto('/');await page.getByRole('button',{name:'Importar partitura',exact:true}).click();await page.getByLabel('Arquivo MusicXML ou MIDI',{exact:true}).setInputFiles({name:'tema.mid',mimeType:'audio/midi',buffer:Buffer.from(midi.toArray())});await expect(page.getByText('PARTITURA RECONHECIDA')).toBeVisible();await expect(page.locator('.warnings')).toContainText('Importado de MIDI');await page.getByRole('button',{name:'Salvar e praticar'}).click();await page.getByRole('button',{name:'Reproduzir',exact:true}).click();await expect(page.getByRole('button',{name:'Pausar',exact:true})).toBeVisible();await page.getByRole('button',{name:'Pausar',exact:true}).click();await page.reload();await expect(page.getByRole('button',{name:'Melodia MIDI de teste',exact:true})).toBeVisible();
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await context.setOffline(true);await page.reload();await expect(page.getByRole('button',{name:'Melodia MIDI de teste',exact:true})).toBeVisible();await page.getByRole('button',{name:'Importar partitura',exact:true}).click();await page.getByLabel('Arquivo MusicXML ou MIDI',{exact:true}).setInputFiles({name:'tema2.midi',mimeType:'audio/midi',buffer:Buffer.from(midi.toArray())});await expect(page.getByText('PARTITURA RECONHECIDA')).toBeVisible();
});
test('real geek search and direct MIDI import stay entirely inside the app',async({page,context})=>{
 test.skip(!live,'Live catalogue checks are opt-in.');const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.getByRole('button',{name:'Explorar',exact:true}).click();await expect(page.getByRole('combobox',{name:'Fonte de partituras'})).toContainText('Ichigo');await page.getByRole('textbox',{name:'Buscar no catálogo'}).fill('Song of Storms');await page.getByRole('button',{name:'Buscar partituras'}).click();await expect(page.locator('.catalog-result').first()).toContainText('Zelda');await expect(page.locator('.catalog-result').first()).toContainText('TinCan');
 await page.locator('.catalog-result').first().getByRole('button',{name:'Créditos'}).click();await expect(page.getByRole('dialog')).toContainText('não comercial');await page.getByRole('button',{name:'Voltar ao catálogo'}).click();await expect(page.getByRole('dialog')).toBeHidden();
 await page.screenshot({path:'../../work/qa-geek-desktop.png',fullPage:true});for(const width of [390,320]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`../../work/qa-geek-${width}.png`,fullPage:true});}
 await page.locator('.catalog-result').first().getByRole('button',{name:'Importar',exact:true}).click();await expect(page.getByText('PARTITURA RECONHECIDA')).toBeVisible();await expect(page.locator('.warnings')).toContainText('TinCan');const save=page.getByRole('button',{name:'Salvar e praticar'});if(await save.isDisabled()){await page.getByRole('combobox',{name:'Como tratar acordes e sobreposições'}).click();await page.getByRole('option',{name:'Manter a nota mais aguda',exact:true}).click();}await save.click();await expect(page.getByRole('heading',{name:'Song of Storms',exact:true})).toBeVisible();await page.getByRole('button',{name:'Reproduzir',exact:true}).click();await expect(page.getByRole('button',{name:'Pausar',exact:true})).toBeVisible();expect(context.pages()).toHaveLength(1);expect(errors).toEqual([]);await page.reload();await expect(page.getByRole('button',{name:'Song of Storms',exact:true})).toBeVisible();
});
test('real Archive popularity, pagination, compatible file resolution and matching offline cache',async({page,context})=>{
 test.skip(!live,'Live catalogue checks are opt-in.');await page.goto('/');await page.getByRole('button',{name:'Explorar',exact:true}).click();await source(page,'Internet Archive · PublicJukebox');await expect(page.getByRole('combobox',{name:'Ordenar catálogo'})).toContainText('Mais populares');await page.getByRole('button',{name:'Buscar partituras'}).click();await expect(page.locator('.catalog-result').first()).toContainText('acessos no Archive');const first=await page.locator('.catalog-result h2').first().innerText();
 const values=await page.locator('.catalog-popularity').allTextContents();const nums=values.map(s=>Number(s.split(' acessos')[0].replace(/\D/g,'')));expect(nums.every((n,i)=>i===0||nums[i-1]>=n)).toBe(true);await page.getByRole('button',{name:'Próxima',exact:true}).click();await expect(page.getByRole('navigation',{name:'Páginas do catálogo'})).toContainText('Página 2');expect(await page.locator('.catalog-result h2').first().innerText()).not.toBe(first);
 await page.getByRole('textbox',{name:'Buscar no catálogo'}).fill('Auld');await page.getByRole('button',{name:'Buscar partituras'}).click();await expect(page.locator('.catalog-result').first()).toContainText('Auld Lang Syne');await page.locator('.catalog-result').first().getByRole('button',{name:'Importar',exact:true}).click();await expect(page.getByText('PARTITURA RECONHECIDA')).toBeVisible();
 await page.getByRole('button',{name:'Explorar',exact:true}).click();await source(page,'Internet Archive · PublicJukebox');await page.getByRole('textbox',{name:'Buscar no catálogo'}).fill('Auld');await context.setOffline(true);await page.getByRole('button',{name:'Buscar partituras'}).click();await expect(page.locator('.catalog-status')).toContainText('Resultados em cache');await expect(page.locator('.catalog-result').first()).toContainText('Auld Lang Syne');
 await page.getByRole('textbox',{name:'Buscar no catálogo'}).fill('no cached query');await page.getByRole('button',{name:'Buscar partituras'}).click();await expect(page.locator('.catalog-result')).toHaveCount(0);
});
test('real PDMX no-conflict search imports an MXL and reaches practice',async({page})=>{
 test.skip(!live,'Live catalogue checks are opt-in.');await page.goto('/');await page.getByRole('button',{name:'Explorar',exact:true}).click();await source(page,'PDMX · domínio público');await page.getByRole('textbox',{name:'Buscar no catálogo'}).fill('Amazing Grace');await page.getByRole('button',{name:'Buscar partituras'}).click();const result=page.locator('.catalog-result').first();await expect(result).toContainText('Amazing Grace');await expect(result).toContainText('CC0');await result.getByRole('button',{name:'Importar',exact:true}).click();await expect(page.getByText('PARTITURA RECONHECIDA')).toBeVisible();await expect(page.locator('.warnings')).toContainText('no_license_conflict');const save=page.getByRole('button',{name:'Salvar e praticar'});if(await save.isDisabled()){await page.getByRole('combobox',{name:'Como tratar acordes e sobreposições'}).click();await page.getByRole('option',{name:'Manter a nota mais aguda',exact:true}).click();}await save.click();await expect(page.getByRole('heading',{name:'Amazing Grace',exact:true})).toBeVisible();await page.getByRole('button',{name:'Reproduzir',exact:true}).click();await expect(page.getByRole('button',{name:'Pausar',exact:true})).toBeVisible();
});
