import {it,expect,vi,afterEach} from 'vitest';
import {Player,timeline,secondsAt} from '../core/audio/player';
import {parseMusicXML} from '../core/music/xml';
import {makeMelody,suggestedSettings} from '../core/music/melody';
import {demoXML} from '../core/music/demo';
const s=parseMusicXML(demoXML),m=makeMelody(s,suggestedSettings(s));
function context(){const nodes:any[]=[];const ctx:any={currentTime:0,destination:{},resume:async()=>{},close:async()=>{},createGain:()=>({gain:{value:0,setValueAtTime:vi.fn(),linearRampToValueAtTime:vi.fn(),setTargetAtTime:vi.fn()},connect:vi.fn(),disconnect:vi.fn()}),createOscillator:()=>{const o={type:'',frequency:{value:0},start:vi.fn(),stop:vi.fn(),connect:vi.fn(),disconnect:vi.fn(),onended:null};nodes.push(o);return o;}};return {ctx,nodes};}
afterEach(()=>vi.useRealTimers());
it('integrates tempo changes, preserves timeline and merges tied attacks',()=>{expect(secondsAt(6,[{at:0,bpm:60},{at:4,bpm:120}])).toBe(5);const data=timeline(m);expect(data.starts).toHaveLength(m.events.length);expect(data.segments).toHaveLength(m.events.filter(e=>e.pitch).length-2);expect(data.segments.some(e=>e.end-e.start===1.5)).toBe(true);});
it('shares audio clock with visuals, cancels scheduled notes on pause, seek, speed and replacement',async()=>{vi.useFakeTimers();const {ctx,nodes}=context(),p=new Player(()=>ctx);p.load(m);await p.play();expect(nodes.length).toBeGreaterThan(0);const active=[...p.nodes];ctx.currentTime=.8;p.tick();expect(p.index).toBe(1);p.pause();expect(p.nodes.size).toBe(0);expect(active.every(n=>(n.stop as any).mock.calls.length>=2)).toBe(true);const paused=p.position;ctx.currentTime=4;expect(p.current()).toBe(paused);await p.play();p.setSpeed(.5);await Promise.resolve();await Promise.resolve();expect(p.speed).toBe(.5);p.seek(10);await Promise.resolve();expect(p.index).toBe(10);p.load(m);expect(p.playing).toBe(false);expect(p.nodes.size).toBe(0);p.dispose();});
it('does not resume after a late AudioContext promise, and clips loop audio',async()=>{vi.useFakeTimers();const {ctx}=context();let resume!:()=>void;ctx.resume=()=>new Promise<void>(r=>resume=r);const p=new Player(()=>ctx);p.load(m);const playing=p.play();p.pause();resume();await playing;expect(p.playing).toBe(false);ctx.resume=async()=>{};p.setLoop(0,0,true);await p.play();ctx.currentTime=3.1;p.tick();expect(p.current()).toBeCloseTo(.1);expect(p.playing).toBe(true);p.dispose();});
it('count-in produces clicks before music, then starts first note',async()=>{vi.useFakeTimers();const {ctx,nodes}=context(),p=new Player(()=>ctx);p.load(m);await p.play(true);expect(p.count).toBe(4);expect(nodes[0].frequency.value).toBe(1100);ctx.currentTime=3;p.tick();expect(p.count).toBe(0);expect(p.index).toBe(0);expect(nodes.some(n=>Math.abs(n.frequency.value-523.251)<.1)).toBe(true);p.dispose();});
