import {describe,it,expect} from 'vitest';
import {zipSync,strToU8} from 'fflate';
import {parseMusicXML,readMusicFile} from '../core/music/xml';
import {makeMelody,suggestedSettings} from '../core/music/melody';
import {fingering,altoC,transposeEvents,suggestTranspositions} from '../core/music/profile';
import {demoXML} from '../core/music/demo';
const note=(step='C',octave=5,duration=1,extra='')=>`<note><pitch><step>${step}</step><octave>${octave}</octave></pitch><duration>${duration}</duration>${extra}</note>`;
const score=(body:string,part2='')=>`<score-partwise><work><work-title>Teste</work-title></work><identification><creator type="composer">Autor</creator></identification><part-list><score-part id="P1"><part-name>Flauta</part-name></score-part><score-part id="P2"><part-name>Baixo</part-name></score-part></part-list><part id="P1">${body}</part>${part2}</score-partwise>`;
const measure=(body:string,attributes='')=>`<measure number="1" ${attributes}>${body}</measure>`;
function makeFile(bytes:Uint8Array,name:string){return {name,size:bytes.length,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)} as File;}
describe('MusicXML',()=>{
 it('parses original demo, metadata, durations, rests, dotted notes, tuplets and ties',()=>{const s=parseMusicXML(demoXML);expect(s.title).toBe('Jardim ao anoitecer');expect(s.composer).toContain('Sopro');const e=s.parts[0].events;expect(e.some(e=>!e.pitch)).toBe(true);expect(e.find(e=>e.dots)?.duration).toBe(1.5);expect(e.find(e=>e.tuplet)?.duration).toBeCloseTo(2/3);expect(e.filter(e=>e.tieStart)).toHaveLength(1);expect(e.filter(e=>e.tieStop)).toHaveLength(1);expect(s.parts[0].tempos).toEqual([{at:0,bpm:80},{at:16,bpm:92}]);});
 it('respects pitch alter including natural in a sharp key, double accidentals and octave',()=>{const s=parseMusicXML(score(measure('<attributes><key><fifths>1</fifths></key></attributes>'+note('F')+'<note><pitch><step>F</step><alter>1</alter><octave>5</octave></pitch><duration>1</duration></note><note><pitch><step>B</step><alter>-2</alter><octave>4</octave></pitch><duration>1</duration></note>')));expect(s.parts[0].events.map(e=>e.pitch?.midi)).toEqual([77,78,69]);expect(s.parts[0].measures[0].fifths).toBe(1);});
 it('keeps backup, forward, staff/voices and explicit gaps',()=>{const s=parseMusicXML(score(measure(note('C',5,2,'<voice>1</voice>')+'<backup><duration>2</duration></backup>'+note('E',4,1,'<voice>2</voice><staff>2</staff>')+'<forward><duration>1</duration></forward>'+note('G',4,1,'<voice>2</voice><staff>2</staff>'))));expect(s.parts[0].events.map(e=>e.start)).toEqual([0,0,2]);const m=makeMelody(s,{...suggestedSettings(s),voice:'2:2'});expect(m.events.map(e=>[e.start,!!e.pitch])).toEqual([[0,true],[1,false],[2,true],[3,false]]);});
 it('supports multiple parts and suggests high melodic instrument',()=>{const s=parseMusicXML(score(measure(note()),`<part id="P2">${measure(note('C',2))}</part>`));expect(s.parts).toHaveLength(2);expect(suggestedSettings(s).partId).toBe('P1');});
 it('automatically reduces chords while retaining the manual voice policy',()=>{const s=parseMusicXML(score(measure(note()+'<note><chord/><pitch><step>E</step><octave>5</octave></pitch><duration>1</duration></note>')));const base=suggestedSettings(s);expect(base.policy).toBe('highest');expect(makeMelody(s,base).events[0].pitch?.midi).toBe(76);expect(makeMelody(s,{...base,policy:'voice'}).events).toHaveLength(0);expect(makeMelody(s,{...base,policy:'lowest'}).events[0].pitch?.midi).toBe(72);});
 it('keeps sustained voices after another note ends',()=>{const s=parseMusicXML(score(measure(note('C',5,4,'<voice>1</voice>')+'<backup><duration>4</duration></backup>'+note('G',5,1,'<voice>2</voice>'))));const m=makeMelody(s,{...suggestedSettings(s),voice:'all',policy:'highest'});expect(m.events.filter(e=>e.pitch).map(e=>[e.pitch?.midi,e.start,e.duration])).toEqual([[79,0,1],[72,1,3]]);});
 it('handles pickup, meter change and instrument transpose',()=>{const s=parseMusicXML(score(measure('<attributes><divisions>2</divisions><time><beats>3</beats><beat-type>8</beat-type></time><transpose><chromatic>-2</chromatic></transpose></attributes>'+note('D',5,1),'implicit="yes"')+'<measure number="2"><attributes><time><beats>6</beats><beat-type>8</beat-type></time></attributes>'+note('D',5,6)+'</measure>'));expect(s.parts[0].measures.map(m=>m.duration)).toEqual([.5,3]);expect(s.parts[0].events[0].pitch?.midi).toBe(72);});
 it('expands simple repeats',()=>{const s=parseMusicXML(demoXML),m=makeMelody(s,suggestedSettings(s));expect(m.measures.map(m=>m.label)).toEqual(['1','2','3','4','1','2','3','4','5','6','7','8']);expect(m.tempos.find(t=>t.at===32)?.bpm).toBe(92);});
 it('expands first and second endings without replaying first ending',()=>{const s=parseMusicXML(score('<measure number="1">'+note()+'<barline location="left"><repeat direction="forward"/></barline></measure><measure number="2">'+note('D')+'<barline location="left"><ending number="1" type="start"/></barline><barline><ending number="1" type="stop"/><repeat direction="backward"/></barline></measure><measure number="3">'+note('E')+'<barline location="left"><ending number="2" type="start"/></barline><barline><ending number="2" type="stop"/></barline></measure>'));expect(makeMelody(s,suggestedSettings(s)).measures.map(m=>m.label)).toEqual(['1','2','1','3']);});
 it('accepts standard external MusicXML declaration without resolving it',()=>expect(parseMusicXML('<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 4.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">'+score(measure(note()))).parts).toHaveLength(1));
 it('rejects entities, malformed XML, excessive size, unsupported roots and impossible timing',()=>{expect(()=>parseMusicXML('<!DOCTYPE x [<!ENTITY ext SYSTEM "file:///etc/passwd">]><x/>')).toThrow(/Entidades/);expect(()=>parseMusicXML('<score-partwise>')).toThrow(/XML inválido/);expect(()=>parseMusicXML('<score-timewise/>')).toThrow(/score-partwise/);expect(()=>parseMusicXML(score(measure('<backup><duration>3</duration></backup>'+note())))).toThrow(/Backup/);expect(()=>parseMusicXML(' '.repeat(8*1024*1024+1))).toThrow(/8 MB/);});
 it('warns for grace, microtones and unsupported jumps',()=>{const s=parseMusicXML(score(measure('<direction><sound dacapo="yes"/></direction><note><grace/><pitch><step>C</step><octave>5</octave></pitch></note><note><pitch><step>C</step><alter>.5</alter><octave>5</octave></pitch><duration>1</duration></note>')));expect(s.warnings.join(' ')).toMatch(/adorno/);expect(s.warnings.join(' ')).toMatch(/Microtons/);expect(makeMelody(s,suggestedSettings(s)).events[0].outOfRange).toBe(true);});
 it('imports compressed MXL container and plain XML',async()=>{const bytes=zipSync({'META-INF/container.xml':strToU8('<container><rootfiles><rootfile full-path="music/main.musicxml"/></rootfiles></container>'),'music/main.musicxml':strToU8(demoXML)});expect(parseMusicXML(await readMusicFile(makeFile(bytes,'demo.mxl'))).parts[0].measures).toHaveLength(8);expect(await readMusicFile(makeFile(strToU8(demoXML),'demo.xml'))).toBe(demoXML);});
 it('rejects ZIP bombs, traversal and missing root',async()=>{await expect(readMusicFile(makeFile(zipSync({'big.xml':strToU8('a'.repeat(2*1024*1024))}),'bomb.mxl'))).rejects.toThrow(/descompressão/);await expect(readMusicFile(makeFile(zipSync({'../bad.xml':strToU8('<x/>')}),'bad.mxl'))).rejects.toThrow(/caminhos/);await expect(readMusicFile(makeFile(zipSync({'a.xml':strToU8('<x/>')}),'bad.mxl'))).rejects.toThrow(/container/);});
});
describe('fingering profile',()=>{
 it('has exactly 12 apertures, two small and two thumb, and 21 chromatic notes A4-F6',()=>{expect(altoC.holes).toHaveLength(12);expect(altoC.holes.filter(h=>h.r===5)).toHaveLength(2);expect(altoC.patterns).toHaveLength(21);expect(altoC.patterns.every(p=>/^[01]{12}$/.test(p))).toBe(true);expect(fingering(69)).toEqual(Array(12).fill(1));expect(fingering(89)).toEqual(Array(12).fill(0));expect(fingering(72)?.slice(8,10)).toEqual([0,0]);expect(fingering(86)?.slice(10)).toEqual([0,1]);});
 it('matches cross-fingered F# and high D# in manufacturer chart',()=>{expect(fingering(75)).toEqual([1,1,1,1,1,1,0,0,0,1,1,1]);expect(fingering(78)).toEqual([1,1,1,1,0,0,1,0,0,0,1,1]);expect(fingering(87)).toEqual([0,0,0,1,0,0,1,0,0,0,0,0]);});
 it('detects out of range and suggests a transparent octave shift',()=>{const s=parseMusicXML(score(measure(note('C',4))));const e=s.parts[0].events;expect(transposeEvents(e,0)[0].outOfRange).toBe(true);expect(transposeEvents(e,12)[0].pitch?.midi).toBe(72);expect(transposeEvents(e,12)[0].outOfRange).toBe(false);expect(e[0].pitch?.midi).toBe(60);expect(suggestTranspositions(e)[0].fit).toBe(1);expect(fingering(90)).toBeUndefined();});
});

it('imports the actual OpenScore CC0 compressed multi-part score',async()=>{const {readFileSync}=await import('node:fs');const bytes=new Uint8Array(readFileSync('tests/fixtures/openscore-lc6583477.mxl'));const s=parseMusicXML(await readMusicFile(makeFile(bytes,'real.mxl')));expect(s.parts.length).toBeGreaterThan(1);expect(s.parts[0].measures.length).toBeGreaterThan(10);const m=makeMelody(s,suggestedSettings(s));expect(m.events.some(e=>e.pitch)).toBe(true);});
