import {Parser} from 'htmlparser2';
import type {CatalogConnector,CatalogResult,CatalogOptions} from './types';
import {CatalogCache,VGLEADSHEETS_INDEX,safeFetch,cachedDownload,allowedURL} from './http';

const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const page=(results:CatalogResult[],source:string,sort:string,number=1)=>{if(sort==='title')results.sort((a,b)=>a.title.localeCompare(b.title,'pt-BR'));const pageSize=20;return {results:results.slice((number-1)*pageSize,number*pageSize),total:results.length,page:number,pageSize,fetchedAt:new Date().toISOString(),source,sort:sort as 'relevance'|'title'};};

function csvRows(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}return rows;}
const vgCache=new CatalogCache<CatalogResult[]>(1,1024*1024);
async function vgLeadIndex(){return vgCache.get('index',async()=>{const rows=csvRows(new TextDecoder().decode(await safeFetch(VGLEADSHEETS_INDEX,2*1024*1024))),seen=new Set<string>(),results:CatalogResult[]=[];for(const [artist,title] of rows.slice(1)){const game=artist?.trim(),name=title?.trim(),key=normalize(`${game}\0${name}`);if(!game||!name||seen.has(key))continue;seen.add(key);results.push({id:`vgl-${results.length+1}`,source:'vgleadsheets',title:name,composer:'Compositor não informado',author:'VGLeadSheets',work:game,license:'Uso educacional · direitos dos autores',formats:['PDF'],pageUrl:'https://vgleadsheets.com/',importable:false,warning:'A fonte oferece PDF, formato que o Sopro não converte. O item aparece apenas como referência no catálogo.'});}return results;},3600000);}
export const vgLeadSheets:CatalogConnector={id:'vgleadsheets',name:'VGLeadSheets',sorts:['relevance','title'],async search(q,options={}){const terms=normalize(q).split(/\s+/).filter(Boolean),rows=(await vgLeadIndex()).filter(r=>terms.every(t=>normalize(`${r.work} ${r.title}`).includes(t)));return page(options.importableOnly===false?rows:[],this.id,options.sort||'relevance',options.page);},async files(){return [];},async download(){throw Error('VGLeadSheets oferece PDF, ainda não importável no Sopro.');}};

type ZeldaRow={result:CatalogResult;url:string};const zeldaCache=new CatalogCache<ZeldaRow[]>(1,2*1024*1024);
export function parseZeldaPage(html:string,section:number){const rows:ZeldaRow[]=[];let game='',title='',capture='';const parser=new Parser({onopentag(tag,attrs){if(tag==='h1'||tag==='h2'){title='';capture=tag;}if(tag==='a'&&title&&/^[A-Za-z0-9_-]+\.mid$/i.test(attrs.href||'')){const url=`https://www.classiczelda.com/music/midi/zelda${section}/${attrs.href}`;allowedURL(url);rows.push({url,result:{id:`zc-${section}-${attrs.href!.toLowerCase()}`,source:'zelda-central',title,work:game,composer:'Compositor original não informado',author:"Ice’s Zelda Central",license:'Uso pessoal · direitos dos autores',formats:['MIDI'],pageUrl:`https://www.classiczelda.com/music/midi/zelda${section}/index.php`,fileUrl:url,importable:true,warning:'Arquivo MIDI público do Ice’s Zelda Central. Escolha a faixa melódica e mantenha os créditos do arranjo.'}});}},ontext(text){if(capture)title+=text;},onclosetag(tag){if(tag==='h1'){game=title.replace(/\s*MIDI Files\s*$/i,'').trim();title='';capture='';}else if(tag==='h2'){title=title.trim();capture='';}}},{decodeEntities:true});parser.end(html);return rows;}
async function zeldaIndex(){return zeldaCache.get('index',async()=>{const groups=await Promise.all([1,2,3,4,5,6].map(async n=>parseZeldaPage(new TextDecoder().decode(await safeFetch(`https://www.classiczelda.com/music/midi/zelda${n}/index.php`,1024*1024)),n)));const seen=new Set<string>();return groups.flat().filter(e=>!seen.has(e.result.id)&&!!seen.add(e.result.id));},3600000);}
export const zeldaCentral:CatalogConnector={id:'zelda-central',name:'Zelda Central MIDI',sorts:['relevance','title'],async search(q,options={}){const terms=normalize(q).split(/\s+/).filter(Boolean),rows=(await zeldaIndex()).filter(e=>terms.every(t=>normalize(`${e.result.work} ${e.result.title}`).includes(t)));return page(rows.map(e=>e.result),this.id,options.sort||'relevance',options.page);},async files(id){const e=(await zeldaIndex()).find(x=>x.result.id===id);if(!e)throw Error('MIDI não encontrado.');return [{name:e.url.split('/').at(-1)!,format:'MIDI',url:e.url}];},async download(id,file){const [entry]=await this.files(id);if(file&&file!==entry.name)throw Error('Arquivo não encontrado.');const bytes=await cachedDownload(entry.url);if(new TextDecoder().decode(bytes.subarray(0,4))!=='MThd')throw Error('A fonte não entregou um MIDI válido.');return {bytes,name:entry.name};}};

export function unavailableConnector(id:string,name:string,message:string):CatalogConnector{return {id,name,sorts:['relevance','title'],async search(){throw Error(message);},async files(){return [];},async download(){throw Error(message);}};}
