name: Sugerir uma melhoria
description: Proponha uma melhoria para aprendizado, música ou acessibilidade
title: "[Ideia]: "
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: Necessidade
      description: Qual problema esta ideia resolveria?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
    validations:
      required: true
