import type { Song } from '../music/types';
import { parseMusicXML } from '../music/xml';
import { suggestedSettings } from '../music/melody';
const DB='sopro-library',VERSION=1;
function openDB():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{r.result.createObjectStore('songs',{keyPath:'id'});r.result.createObjectStore('preferences');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function transact<T>(store:string,mode:IDBTransactionMode,run:(s:IDBObjectStore)=>IDBRequest<T>):Promise<T>{const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode);const req=run(tx.objectStore(store));tx.oncomplete=()=>{db.close();resolve(req.result);};tx.onabort=tx.onerror=()=>{db.close();reject(tx.error||req.error||Error('Falha ao salvar no dispositivo.'));};});}
export const library={all:()=>transact('songs','readonly',s=>s.getAll()) as Promise<Song[]>,put:(song:Song)=>transact('songs','readwrite',s=>s.put(song)),remove:(id:string)=>transact('songs','readwrite',s=>s.delete(id)),getPreference:<T>(key:string)=>transact('preferences','readonly',s=>s.get(key)) as Promise<T|undefined>,setPreference:(key:string,value:unknown)=>transact('preferences','readwrite',s=>s.put(value,key))};
export function newSong(xml:string):Song {const score=parseMusicXML(xml);return {id:crypto.randomUUID(),xml,score,title:score.title,composer:score.composer,settings:{...suggestedSettings(score),adaptation:'strict'},favorite:false,createdAt:Date.now()};}
export async function exportBackup(){return JSON.stringify({format:'sopro-backup',version:1,exportedAt:new Date().toISOString(),songs:await library.all(),preferences:await library.getPreference('general')},null,2);}
export async function importBackup(text:string){if(text.length>30*1024*1024)throw Error('Backup excede 30 MB.');const data=JSON.parse(text);if(data.format!=='sopro-backup'||data.version!==1||!Array.isArray(data.songs)||data.songs.length>200)throw Error('Backup Sopro inválido ou incompatível.');
 const songs:Song[]=data.songs.map((s:Song)=>{if(typeof s.xml!=='string'||typeof s.id!=='string'||s.id.length>100)throw Error('Música inválida no backup.');const parsed=newSong(s.xml),setting=s.settings||parsed.settings;
 if(!parsed.score.parts.some(p=>p.id===setting.partId&& (setting.voice==='all'||p.voices.includes(setting.voice)))||!['voice','highest','lowest'].includes(setting.policy)||!Number.isInteger(setting.transpose)||Math.abs(setting.transpose)>24||!Number.isFinite(setting.speed)||setting.speed<.25||setting.speed>2)throw Error('Configuração inválida no backup.');
 if(setting.adaptation&&!['original','strict','balanced','flexible'].includes(setting.adaptation)||setting.simplify!==undefined&&typeof setting.simplify!=='boolean')throw Error('Adaptação inválida no backup.');
 return {...parsed,id:s.id,title:String(s.title||parsed.title).slice(0,300),composer:String(s.composer||parsed.composer).slice(0,300),favorite:!!s.favorite,status:['learning','almost','mastered'].includes(s.status||'')?s.status:'learning',...Object.fromEntries(['source','sourceName','collection','category','license'].filter(k=>typeof s[k as keyof Song]==='string').map(k=>[k,String(s[k as keyof Song]).slice(0,1000)])),settings:{...setting,lastIndex:Math.max(0,Math.floor(Number(setting.lastIndex)||0))},createdAt:Number(s.createdAt)||Date.now(),lastPractice:Number(s.lastPractice)||undefined};});
 const db=await openDB();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(['songs','preferences'],'readwrite');songs.forEach(s=>tx.objectStore('songs').put(s));if(data.preferences&&typeof data.preferences.solfege==='boolean')tx.objectStore('preferences').put({solfege:data.preferences.solfege,...(typeof data.preferences.volume==='number'?{volume:Math.max(0,Math.min(1,data.preferences.volume))}:{}),...Object.fromEntries(['metronome','countIn','fingers','showRests'].filter(k=>typeof data.preferences[k]==='boolean').map(k=>[k,data.preferences[k]]))},'general');tx.oncomplete=()=>{db.close();resolve();};tx.onabort=tx.onerror=()=>{db.close();reject(tx.error);};});return songs.length;
}
export function download(name:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
